- src/pages/lobbies/_lobbyId/play/AdminPanel.js
- src/pages/lobbies/_lobbyId/play/UserPanel.js
Reseting lastBall call when board is restart
> Reseting lastBall

- src/components/common/arrowsCarousel.js
Adding cursor pointer to carousel arrows
> adding cursor pointer

- package-lock.json
- src/pages/login/NicknameStep.js
- src/pages/login/PinStep.js
Removing autocomplete for input nickname
> removing autocomplete

- package-lock.json
- src/pages/lobbies/_lobbyId/play/UserProgress.js
- src/pages/lobbies/_lobbyId/play/UsersTabs.js
refactoring user winner and fixing design
> order user by percentage

- src/pages/lobbies/_lobbyId/play/ModalAwards.js
> Disable input award

- src/pages/login/NicknameStep.js
fixing user loggin after game started
> fixing user loggin

- src/pages/lobbies/_lobbyId/play/AdminPanel.js
- src/pages/lobbies/_lobbyId/play/LastBall.js
- src/pages/lobbies/_lobbyId/play/ModalFinalStage.js
- src/pages/lobbies/_lobbyId/play/ModalUserCard.js
- src/pages/lobbies/_lobbyId/play/UserPanel.js
Buttons sizes
Lastball fixed
Awards can have same name
> Las focus group feedbacks

- src/components/form/Anchor.js
- src/pages/login/index.js
> returning to pin step

- src/pages/lobbies/_lobbyId/play/UserProgress.js
- src/pages/lobbies/_lobbyId/play/UsersTabs.js
Fixing order and removing unnecessary fetchs
> fixing user tabs order

- src/pages/lobbies/_lobbyId/play/LobbyInPlay.js
Hacer una consulta del lobby antes de llamar a bingo, considerando que el onSnapshot nos provee el lobby por props tiene un delay al reflejar el cambio, tambien se puede asumir que existe un delay entre llamar al modal para bloquear la pantalla del usario
> verificar antes de llamar a bingo

- src/pages/lobbies/_lobbyId/play/AdminPanel.js
- src/pages/lobbies/_lobbyId/play/LastBall.js
- src/pages/lobbies/_lobbyId/play/LastPlays.js
- src/pages/lobbies/_lobbyId/play/SliderControls.js
- src/pages/lobbies/_lobbyId/play/UserPanel.js
> fixing animation

- package-lock.json
- src/components/common/FileUpload.js
- src/components/form/Button.js
- src/pages/lobbies/_lobbyId/CreateLobby.js
- src/pages/lobbies/_lobbyId/play/ModalAwards.js
- src/pages/lobbies/_lobbyId/play/ModalFinalStage.js
- src/pages/lobbies/_lobbyId/play/ModalUserCard.js
- tailwind.config.js
New awards design with upload image
> New design awards

- src/pages/lobbies/_lobbyId/play/UserPanel.js
Removing extra balls and fixing design for user
> Fixing user design

- src/components/common/FileUpload.js
- src/pages/lobbies/_lobbyId/play/LobbyInPlay.js
- src/pages/lobbies/_lobbyId/play/ModalAwards.js
> Fixing awards design and setting display chat to false by default

- src/pages/lobbies/_lobbyId/play/ModalUserCard.js
fixing buttons colors and missing button
> modal user card buttons

- package-lock.json
- src/components/common/FileUpload.js
- src/constants/responsive.js
- src/pages/lobbies/_lobbyId/play/ModalAwards.js
- src/pages/lobbies/_lobbyId/play/ModalFinalStage.js
- src/pages/lobbies/_lobbyId/play/ModalUserCard.js
- src/pages/lobbies/_lobbyId/play/ModalWinner.js
- src/pages/lobbies/_lobbyId/play/Ribbon.js
> new design modals

- cloudbuild-preview.yaml
- pages/404.js
- pages/500.js
- pages/_app.js
- pages/bingo/lobbies/[lobbyId]/index.js
- src/components/form/Anchor.js
- src/components/form/Button.js
- src/pages/lading/index.js
- src/pages/lobbies/_lobbyId/CreateLobby.js
- src/pages/lobbies/_lobbyId/LobbyHeader.js
- src/pages/lobbies/_lobbyId/LobbyLoading.js
- src/pages/lobbies/_lobbyId/play/LastBall.js
- src/pages/lobbies/_lobbyId/play/UserCard.js
- src/pages/lobbies/_lobbyId/play/UsersTabs.js
- src/pages/lobbies/_lobbyId/userLayout.js
- tailwind.config.js
https://www.notion.so/ebombo/Mejorar-este-dise-o-Preparate-2-ca96d740190e46fea87bc98bb44b3b21
> format & new tiitle loader

- src/pages/lobbies/_lobbyId/play/ModalFinalStage.js
Making a copy  of the lobby to bombo-games
> making a copy to bombo-games

- src/pages/lobbies/_lobbyId/CreateLobby.js
> adding deleted property

- src/pages/lobbies/_lobbyId/LobbyUser.js
https://www.notion.so/ebombo/TECH-TASK-8ab20c64c6fe427385e6247091f186a8?v=ec3114d9344d40789fec0947275ed11c&p=2a5fd7b6863c4cb38dc0994f9b09e0ec
> replaced classes and fix text-overflow
